"""Write FontCoverage.kt: which code points each design-named face can draw, read out of its cmap.

The per-script join (research D6) moves a run to the companion face when the design's own face
cannot draw it. "Cannot draw" is decided by the face's cmap, not by "is it Cyrillic" — kvadrant-ui
approximated coverage with a script test and a password mask character fell out of both faces
(its KvadrantText.kt). The table is generated so it cannot drift from the files;
`FontCoverageTest` re-derives it on the JVM from the same files and fails on any difference, so
this script does not need to run inside the gate.

Needs fontTools. Run after changing a font file:  python3 scripts/fonts/generate_coverage.py
"""

import pathlib

from fontTools.ttLib import TTFont

ROOT = pathlib.Path(__file__).resolve().parents[2]
FONTS = ROOT / "oldge-core/src/commonMain/composeResources/font"
OUT = ROOT / "oldge-core/src/commonMain/kotlin/io/github/youndie/oldge/type/FontCoverage.kt"

# Only the faces a companion stands beside. The others carry full Cyrillic and are checked against
# the design system's strings by DesignStringCoverageTest instead.
FACES = {"shareTechMono": "share_tech_mono.ttf", "silkscreen": "silkscreen.ttf"}


def ranges(cmap):
    cps = sorted(cp for cp in cmap if cp >= 0x20)
    out = []
    for cp in cps:
        if out and cp == out[-1][1] + 1:
            out[-1][1] = cp
        else:
            out.append([cp, cp])
    return out


def main():
    lines = [
        "// GENERATED by scripts/fonts/generate_coverage.py from the files in composeResources/font.",
        "// Do not edit: FontCoverageTest re-derives every range from the font files and fails on a",
        "// difference.",
        "package io.github.youndie.oldge.type",
        "",
        "/** Inclusive code point ranges, as `[first0, last0, first1, last1, ...]`, per face. */",
        "internal object FontCoverage {",
    ]
    for prop, file in FACES.items():
        rs = ranges(TTFont(str(FONTS / file)).getBestCmap())
        lines.append(f"    /** `{file}`: {len(rs)} ranges. */")
        lines.append(f"    val {prop}: IntArray =")
        lines.append("        intArrayOf(")
        # One value per line: ktlint's argument wrapping allows nothing else for a multi-line call.
        lines += [f"            0x{v:04X}," for a, b in rs for v in (a, b)]
        lines.append("        )")
        lines.append("")
    lines[-1:] = ["}", ""]
    OUT.write_text("\n".join(lines))
    print(OUT.relative_to(ROOT))


if __name__ == "__main__":
    main()
