// GENERATED by scripts/generate_icons.py from reference/design-system/components/bundle.js.
// Do not edit: `./gradlew check` runs the generator with --check.
// The path strings are the bundle's, verbatim, so they are longer than a line may be.
@file:Suppress("ktlint")

package io.github.youndie.oldge.icons

import androidx.compose.ui.graphics.vector.ImageVector

/** The design system's 47 icons: single-path glyphs on a 24 × 24 grid, filled even-odd. */
public object OldgeIcons {
    /** `home`. */
    public val Home: ImageVector by lazy { oldgeIcon("home", OldgeIconPaths.getValue("home")) }

    /** `search`. */
    public val Search: ImageVector by lazy { oldgeIcon("search", OldgeIconPaths.getValue("search")) }

    /** `gear`. */
    public val Gear: ImageVector by lazy { oldgeIcon("gear", OldgeIconPaths.getValue("gear")) }

    /** `user`. */
    public val User: ImageVector by lazy { oldgeIcon("user", OldgeIconPaths.getValue("user")) }

    /** `bell`. */
    public val Bell: ImageVector by lazy { oldgeIcon("bell", OldgeIconPaths.getValue("bell")) }

    /** `star`. */
    public val Star: ImageVector by lazy { oldgeIcon("star", OldgeIconPaths.getValue("star")) }

    /** `doc`. */
    public val Doc: ImageVector by lazy { oldgeIcon("doc", OldgeIconPaths.getValue("doc")) }

    /** `image`. */
    public val Image: ImageVector by lazy { oldgeIcon("image", OldgeIconPaths.getValue("image")) }

    /** `note`. */
    public val Note: ImageVector by lazy { oldgeIcon("note", OldgeIconPaths.getValue("note")) }

    /** `film`. */
    public val Film: ImageVector by lazy { oldgeIcon("film", OldgeIconPaths.getValue("film")) }

    /** `folder`. */
    public val Folder: ImageVector by lazy { oldgeIcon("folder", OldgeIconPaths.getValue("folder")) }

    /** `disc`. */
    public val Disc: ImageVector by lazy { oldgeIcon("disc", OldgeIconPaths.getValue("disc")) }

    /** `flame`. */
    public val Flame: ImageVector by lazy { oldgeIcon("flame", OldgeIconPaths.getValue("flame")) }

    /** `cloud`. */
    public val Cloud: ImageVector by lazy { oldgeIcon("cloud", OldgeIconPaths.getValue("cloud")) }

    /** `lock`. */
    public val Lock: ImageVector by lazy { oldgeIcon("lock", OldgeIconPaths.getValue("lock")) }

    /** `grid`. */
    public val Grid: ImageVector by lazy { oldgeIcon("grid", OldgeIconPaths.getValue("grid")) }

    /** `download`. */
    public val Download: ImageVector by lazy { oldgeIcon("download", OldgeIconPaths.getValue("download")) }

    /** `upload`. */
    public val Upload: ImageVector by lazy { oldgeIcon("upload", OldgeIconPaths.getValue("upload")) }

    /** `refresh`. */
    public val Refresh: ImageVector by lazy { oldgeIcon("refresh", OldgeIconPaths.getValue("refresh")) }

    /** `plus`. */
    public val Plus: ImageVector by lazy { oldgeIcon("plus", OldgeIconPaths.getValue("plus")) }

    /** `minus`. */
    public val Minus: ImageVector by lazy { oldgeIcon("minus", OldgeIconPaths.getValue("minus")) }

    /** `edit`. */
    public val Edit: ImageVector by lazy { oldgeIcon("edit", OldgeIconPaths.getValue("edit")) }

    /** `trash`. */
    public val Trash: ImageVector by lazy { oldgeIcon("trash", OldgeIconPaths.getValue("trash")) }

    /** `play`. */
    public val Play: ImageVector by lazy { oldgeIcon("play", OldgeIconPaths.getValue("play")) }

    /** `pause`. */
    public val Pause: ImageVector by lazy { oldgeIcon("pause", OldgeIconPaths.getValue("pause")) }

    /** `levels`. */
    public val Levels: ImageVector by lazy { oldgeIcon("levels", OldgeIconPaths.getValue("levels")) }

    /** `back`. */
    public val Back: ImageVector by lazy { oldgeIcon("back", OldgeIconPaths.getValue("back")) }

    /** `chevron`. */
    public val Chevron: ImageVector by lazy { oldgeIcon("chevron", OldgeIconPaths.getValue("chevron")) }

    /** `down`. */
    public val Down: ImageVector by lazy { oldgeIcon("down", OldgeIconPaths.getValue("down")) }

    /** `chevrons`. */
    public val Chevrons: ImageVector by lazy { oldgeIcon("chevrons", OldgeIconPaths.getValue("chevrons")) }

    /** `menu`. */
    public val Menu: ImageVector by lazy { oldgeIcon("menu", OldgeIconPaths.getValue("menu")) }

    /** `close`. */
    public val Close: ImageVector by lazy { oldgeIcon("close", OldgeIconPaths.getValue("close")) }

    /** `check`. */
    public val Check: ImageVector by lazy { oldgeIcon("check", OldgeIconPaths.getValue("check")) }

    /** `help`. */
    public val Help: ImageVector by lazy { oldgeIcon("help", OldgeIconPaths.getValue("help")) }

    /** `info`. */
    public val Info: ImageVector by lazy { oldgeIcon("info", OldgeIconPaths.getValue("info")) }

    /** `warn`. */
    public val Warn: ImageVector by lazy { oldgeIcon("warn", OldgeIconPaths.getValue("warn")) }

    /** `ok`. */
    public val Ok: ImageVector by lazy { oldgeIcon("ok", OldgeIconPaths.getValue("ok")) }

    /** `error`. */
    public val Error: ImageVector by lazy { oldgeIcon("error", OldgeIconPaths.getValue("error")) }

    /** `eye`. */
    public val Eye: ImageVector by lazy { oldgeIcon("eye", OldgeIconPaths.getValue("eye")) }

    /** `eye-off`. */
    public val EyeOff: ImageVector by lazy { oldgeIcon("eye-off", OldgeIconPaths.getValue("eye-off")) }

    /** `attach`. */
    public val Attach: ImageVector by lazy { oldgeIcon("attach", OldgeIconPaths.getValue("attach")) }

    /** `send`. */
    public val Send: ImageVector by lazy { oldgeIcon("send", OldgeIconPaths.getValue("send")) }

    /** `more`. */
    public val More: ImageVector by lazy { oldgeIcon("more", OldgeIconPaths.getValue("more")) }

    /** `heart`. */
    public val Heart: ImageVector by lazy { oldgeIcon("heart", OldgeIconPaths.getValue("heart")) }

    /** `share`. */
    public val Share: ImageVector by lazy { oldgeIcon("share", OldgeIconPaths.getValue("share")) }

    /** `key`. */
    public val Key: ImageVector by lazy { oldgeIcon("key", OldgeIconPaths.getValue("key")) }

    /** `mail`. */
    public val Mail: ImageVector by lazy { oldgeIcon("mail", OldgeIconPaths.getValue("mail")) }
}

/** Every icon's path, by the design system's name, in the bundle's order. */
internal val OldgeIconPaths: Map<String, String> =
    linkedMapOf(
        "home" to "M12 3l9.5 8.5h-3V21h-5v-6h-3v6h-5v-9.5h-3z",
        "search" to "M10 3a7 7 0 1 0 4.2 12.6l5.1 5.1 1.7-1.7-5.1-5.1A7 7 0 0 0 10 3zm0 2.4a4.6 4.6 0 1 1 0 9.2 4.6 4.6 0 0 1 0-9.2z",
        "gear" to "M19.6 10.3 22.1 10.7 22.1 13.3 19.6 13.7 18.6 16.2 20.1 18.2 18.2 20.1 16.2 18.6 13.7 19.6 13.3 22.1 10.7 22.1 10.3 19.6 7.8 18.6 5.8 20.1 3.9 18.2 5.4 16.2 4.4 13.7 1.9 13.3 1.9 10.7 4.4 10.3 5.4 7.8 3.9 5.8 5.8 3.9 7.8 5.4 10.3 4.4 10.7 1.9 13.3 1.9 13.7 4.4 16.2 5.4 18.2 3.9 20.1 5.8 18.6 7.8zM12 8.6a3.4 3.4 0 1 0 0 6.8 3.4 3.4 0 0 0 0-6.8z",
        "user" to "M12 3a4.5 4.5 0 1 1 0 9 4.5 4.5 0 0 1 0-9zM3.5 21c0-4.2 3.8-7 8.5-7s8.5 2.8 8.5 7z",
        "bell" to "M12 2.5c.8 0 1.4.6 1.4 1.4v.7c2.9.7 4.6 3.2 4.6 6.2v4.2l2 2.5v1H4v-1l2-2.5v-4.2c0-3 1.7-5.5 4.6-6.2v-.7c0-.8.6-1.4 1.4-1.4zM9.5 19.5h5a2.5 2.5 0 0 1-5 0z",
        "star" to "M12 2.5l2.9 6 6.6.8-4.9 4.6 1.3 6.6L12 17.2l-5.9 3.3 1.3-6.6-4.9-4.6 6.6-.8z",
        "doc" to "M5 2.5h9l5 5v14H5zM13.2 4v4.3h4.3zM7.5 11h9v1.6h-9zm0 3.2h9v1.6h-9zm0 3.2h6v1.6h-6z",
        "image" to "M3 4.5h18v15H3zM5 6.5v9.3l4-4.3 3 3.2 2.2-2.2 4.8 4.8V6.5zM15.5 8a1.8 1.8 0 1 1 0 3.6 1.8 1.8 0 0 1 0-3.6z",
        "note" to "M9 3.5v10.1A3.6 3.6 0 1 0 11 17V8h7V3.5z",
        "film" to "M3 4h18v16H3zM5 6v2h2V6zm0 5v2h2v-2zm0 5v2h2v-2zM17 6v2h2V6zm0 5v2h2v-2zm0 5v2h2v-2zM9 6v12h6V6z",
        "folder" to "M2.5 5.5A1.5 1.5 0 0 1 4 4h5.2l2 2.2H20a1.5 1.5 0 0 1 1.5 1.5v10.8A1.5 1.5 0 0 1 20 20H4a1.5 1.5 0 0 1-1.5-1.5z",
        "disc" to "M12 2a10 10 0 1 0 0 20 10 10 0 0 0 0-20zm0 7.5a2.5 2.5 0 1 1 0 5 2.5 2.5 0 0 1 0-5zM12 4.5A7.5 7.5 0 0 0 4.5 12H6a6 6 0 0 1 6-6z",
        "flame" to "M13.6 1.5c.4 3.6 4.9 5.8 4.9 11.4a6.5 6.5 0 0 1-13 0c0-3.1 1.6-5.3 3.3-6.8-.1 2.1.9 3.7 2.4 3.7-.1-3.2.7-5.9 2.4-8.3zM12 21.2c-1.9 0-3.3-1.4-3.3-3.3 0-1.9 1.3-3 3.3-5.1 2 2.1 3.3 3.2 3.3 5.1 0 1.9-1.4 3.3-3.3 3.3z",
        "cloud" to "M7 19a5 5 0 0 1-.6-10A6.5 6.5 0 0 1 18.8 10.5 4.3 4.3 0 0 1 18 19z",
        "lock" to "M7 10V7.5a5 5 0 0 1 10 0V10h1.5v11h-13V10zm2.4 0h5.2V7.5a2.6 2.6 0 0 0-5.2 0zM11 14h2v4h-2z",
        "grid" to "M4 4h7v7H4zm9 0h7v7h-7zM4 13h7v7H4zm9 0h7v7h-7z",
        "download" to "M10.8 3h2.4v9.2l3.3-3.3 1.7 1.7L12 16.8l-6.2-6.2 1.7-1.7 3.3 3.3zM4 18.5h16V21H4z",
        "upload" to "M12 3l6.2 6.2-1.7 1.7-3.3-3.3V17h-2.4V7.6L7.5 10.9 5.8 9.2zM4 18.5h16V21H4z",
        "refresh" to "M12 4a8 8 0 0 1 5.7 2.3L20 4v6.5h-6.5l2.5-2.5A5.6 5.6 0 1 0 17.4 13.5h2.4A8 8 0 1 1 12 4z",
        "plus" to "M10.8 4h2.4v6.8H20v2.4h-6.8V20h-2.4v-6.8H4v-2.4h6.8z",
        "minus" to "M4 10.8h16v2.4H4z",
        "edit" to "M16.2 3.3l4.5 4.5L9 19.5l-5.5 1 1-5.5zM14.6 6.1l-1 1 3.3 3.3 1-1z",
        "trash" to "M9 3h6l1 1.5h4.5V7h-17V4.5H8zM5 8.5h14l-1.2 12.5H6.2zM9 11v7.5h1.8V11zm4.2 0v7.5H15V11z",
        "play" to "M8 5v14l11-7z",
        "pause" to "M6 5h4v14H6zM14 5h4v14h-4z",
        "levels" to "M4 13h4v8H4zM10 7h4v14h-4zM16 3h4v18h-4z",
        "back" to "M15.4 4.6L8 12l7.4 7.4 1.8-1.8L11.6 12l5.6-5.6z",
        "chevron" to "M8.6 5.4L10.4 3.6 18.8 12l-8.4 8.4-1.8-1.8L15.2 12z",
        "down" to "M5.4 8.6L3.6 10.4 12 18.8l8.4-8.4-1.8-1.8L12 15.2z",
        "chevrons" to "M12 11.2l-6.3-6.3-1.7 1.7 8 8 8-8-1.7-1.7zm0 6.2l-6.3-6.3-1.7 1.7 8 8 8-8-1.7-1.7z",
        "menu" to "M4 6h16v2.4H4zm0 4.8h16v2.4H4zm0 4.8h16V18H4z",
        "close" to "M6.3 4.5L4.5 6.3 10.2 12l-5.7 5.7 1.8 1.8 5.7-5.7 5.7 5.7 1.8-1.8-5.7-5.7 5.7-5.7-1.8-1.8-5.7 5.7z",
        "check" to "M9 15.6L4.9 11.5 3 13.4l6 6L21 7.4l-1.9-1.9z",
        "help" to "M12 2a10 10 0 1 0 0 20 10 10 0 0 0 0-20zm-.1 4.5c2.2 0 3.8 1.3 3.8 3.2 0 1.5-.9 2.3-1.9 3-.7.5-.9.8-.9 1.6v.4h-2.2v-.6c0-1.3.5-2 1.5-2.7.8-.6 1.2-1 1.2-1.6 0-.8-.6-1.3-1.5-1.3-1 0-1.6.6-1.7 1.5H8c.1-2.1 1.6-3.5 3.9-3.5zM10.8 15.8h2.4v2.3h-2.4z",
        "info" to "M12 2a10 10 0 1 0 0 20 10 10 0 0 0 0-20zM10.8 10h2.4v7.5h-2.4zm0-4h2.4v2.4h-2.4z",
        "warn" to "M12 2.5L1 21.5h22zM10.8 9.5h2.4v6h-2.4zm0 7.5h2.4v2.4h-2.4z",
        "ok" to "M12 2a10 10 0 1 0 0 20 10 10 0 0 0 0-20zM10.5 16.6l-4.3-4.3 1.7-1.7 2.6 2.6 5.6-5.6 1.7 1.7z",
        "error" to "M12 2a10 10 0 1 0 0 20 10 10 0 0 0 0-20zM8.4 6.7L6.7 8.4 10.3 12l-3.6 3.6 1.7 1.7 3.6-3.6 3.6 3.6 1.7-1.7-3.6-3.6 3.6-3.6-1.7-1.7-3.6 3.6z",
        "eye" to "M12 5C6.5 5 2.5 9.3 1 12c1.5 2.7 5.5 7 11 7s9.5-4.3 11-7c-1.5-2.7-5.5-7-11-7zm0 3.2a3.8 3.8 0 1 1 0 7.6 3.8 3.8 0 0 1 0-7.6zm0 2a1.8 1.8 0 1 0 0 3.6 1.8 1.8 0 0 0 0-3.6z",
        "eye-off" to "M12 5C6.5 5 2.5 9.3 1 12c1.5 2.7 5.5 7 11 7s9.5-4.3 11-7c-1.5-2.7-5.5-7-11-7zm0 3.2a3.8 3.8 0 1 1 0 7.6 3.8 3.8 0 0 1 0-7.6zm0 2a1.8 1.8 0 1 0 0 3.6 1.8 1.8 0 0 0 0-3.6zM2.22 3.78 20.22 21.78 21.78 20.22 3.78 2.22Z",
        "attach" to "M6.5 7.5A5 5 0 0 1 16.5 7.5V16.5A5 5 0 0 1 6.5 16.5ZM8.3 7.5A3.2 3.2 0 0 1 14.7 7.5V16.5A3.2 3.2 0 0 1 8.3 16.5ZM9.6 8.4A1.9 1.9 0 0 1 13.4 8.4V14.6A1.9 1.9 0 0 1 9.6 14.6ZM11.4 8.4A0.1 0.1 0 0 1 11.6 8.4V14.6A0.1 0.1 0 0 1 11.4 14.6Z",
        "send" to "M2.5 20.5l19-8.5-19-8.5.02 6.6L14 12 2.52 13.9z",
        "more" to "M12 2.9a2.1 2.1 0 1 0 0 4.2a2.1 2.1 0 1 0 0 -4.2zM12 9.9a2.1 2.1 0 1 0 0 4.2a2.1 2.1 0 1 0 0 -4.2zM12 16.9a2.1 2.1 0 1 0 0 4.2a2.1 2.1 0 1 0 0 -4.2z",
        "heart" to "M12 21s-7.5-4.6-9.6-9.3C.9 8.2 3 4.5 6.6 4.5c2.2 0 3.6 1.2 5.4 3.2 1.8-2 3.2-3.2 5.4-3.2 3.6 0 5.7 3.7 4.2 7.2C19.5 16.4 12 21 12 21z",
        "share" to "M18 2.2a2.8 2.8 0 1 0 0 5.6a2.8 2.8 0 1 0 0 -5.6zM6 9.2a2.8 2.8 0 1 0 0 5.6a2.8 2.8 0 1 0 0 -5.6zM18 16.2a2.8 2.8 0 1 0 0 5.6a2.8 2.8 0 1 0 0 -5.6zM9.33 11.03 16.03 7.13 15.17 5.67 8.47 9.57ZM8.47 14.43 15.17 18.33 16.03 16.87 9.33 12.97Z",
        "key" to "M7.5 7a5 5 0 1 0 0 10a5 5 0 1 0 0 -10zM7.5 10a2 2 0 1 0 0 4a2 2 0 1 0 0 -4zM12.6 11h9.4v2.4h-2V17h-2.4v-3.6H16V16h-2.4v-2.6h-1z",
        "mail" to "M2.5 5h19v14h-19zM4.3 6.8v10.4h15.4V6.8zM4.3 6.8h2.3L12 11l5.4-4.2h2.3v.4L12 13.2 4.3 7.2z",
    )
