package io.github.youndie.oldge.type

import kotlin.test.Test
import kotlin.test.assertEquals

/**
 * [FontCoverage] is generated by `scripts/fonts/generate_coverage.py` with fontTools; this re-derives
 * it on the JVM from the same files, so a font replaced without regenerating fails here rather than
 * silently sending a run to the wrong face.
 */
class FontCoverageTest {
    @Test
    fun share_tech_mono_coverage_matches_its_file() = assertMatches("share_tech_mono.ttf", FontCoverage.shareTechMono)

    @Test
    fun silkscreen_coverage_matches_its_file() = assertMatches("silkscreen.ttf", FontCoverage.silkscreen)

    @Test
    fun the_bundled_file_set_is_exactly_the_seven_faces() =
        assertEquals(BundledFonts.all.sorted(), BundledFonts.files())

    /**
     * AWT reports these as displayable in **every** font, cmap or not — measured: both faces here
     * disagreed with their cmap on exactly this set, 63 code points each. They are Unicode's
     * Default_Ignorable code points, controls and separators, and unassigned specials: nothing a
     * glyph is drawn for, so nothing a run is ever moved for.
     */
    private fun awtClaimsAnyway(codePoint: Int): Boolean =
        DEFAULT_IGNORABLE.any { codePoint in it } ||
            Character.getType(codePoint).toByte().let {
                it == Character.CONTROL || it == Character.LINE_SEPARATOR || it == Character.PARAGRAPH_SEPARATOR
            }

    private fun assertMatches(
        file: String,
        generated: IntArray,
    ) {
        val font = BundledFonts.awt(file)
        val wrong = (0x20..0xFFFF).filter { font.canDisplay(it) != generated.covers(it) && !awtClaimsAnyway(it) }
        assertEquals(
            emptyList(),
            wrong.map { "U+%04X".format(it) },
            "FontCoverage disagrees with $file on ${wrong.size} code points; " +
                "run python3 scripts/fonts/generate_coverage.py",
        )
    }

    private companion object {
        val DEFAULT_IGNORABLE =
            listOf(
                0x034F..0x034F,
                0x061C..0x061C,
                0x115F..0x1160,
                0x17B4..0x17B5,
                0x180B..0x180F,
                0x200B..0x200F,
                0x202A..0x202E,
                0x2060..0x206F,
                0x3164..0x3164,
                0xFE00..0xFE0F,
                0xFEFF..0xFEFF,
                0xFFA0..0xFFA0,
                0xFFF0..0xFFF8,
            )
    }
}
