// GENERATED by scripts/generate_tokens.py from reference/design-system/tokens.json.
// Do not edit: `./gradlew check` runs the generator with --check, and OldgeTokensTest holds every
// value to its own reading of the JSON.
@file:Suppress("ktlint")

package io.github.youndie.oldge.tokens

import androidx.compose.animation.core.CubicBezierEasing
import androidx.compose.animation.core.Easing
import androidx.compose.animation.core.LinearEasing
import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp

/**
 * The design system's colour tokens for one skin. A new skin is a new instance of this class:
 * the components read roles, never values (the design system's README, the section on skins).
 */
@Immutable
public class OldgeColors(
    /** Token `body-hi`; its usage note is in reference/design-system/tokens.json. */
    public val bodyHi: Color,
    /** Token `ground`; its usage note is in reference/design-system/tokens.json. */
    public val ground: Color,
    /** Token `glow`; its usage note is in reference/design-system/tokens.json. */
    public val glow: Color,
    /** Token `surface`; its usage note is in reference/design-system/tokens.json. */
    public val surface: Color,
    /** Token `surface-2`; its usage note is in reference/design-system/tokens.json. */
    public val surface2: Color,
    /** Token `well`; its usage note is in reference/design-system/tokens.json. */
    public val well: Color,
    /** Token `ink`; its usage note is in reference/design-system/tokens.json. */
    public val ink: Color,
    /** Token `ink-muted`; its usage note is in reference/design-system/tokens.json. */
    public val inkMuted: Color,
    /** Token `line`; its usage note is in reference/design-system/tokens.json. */
    public val line: Color,
    /** Token `edge`; its usage note is in reference/design-system/tokens.json. */
    public val edge: Color,
    /** Token `gloss`; its usage note is in reference/design-system/tokens.json. */
    public val gloss: Color,
    /** Token `bezel-hi`; its usage note is in reference/design-system/tokens.json. */
    public val bezelHi: Color,
    /** Token `bezel`; its usage note is in reference/design-system/tokens.json. */
    public val bezel: Color,
    /** Token `bezel-lo`; its usage note is in reference/design-system/tokens.json. */
    public val bezelLo: Color,
    /** Token `on-bezel`; its usage note is in reference/design-system/tokens.json. */
    public val onBezel: Color,
    /** Token `chrome-hi`; its usage note is in reference/design-system/tokens.json. */
    public val chromeHi: Color,
    /** Token `chrome-lo`; its usage note is in reference/design-system/tokens.json. */
    public val chromeLo: Color,
    /** Token `on-chrome`; its usage note is in reference/design-system/tokens.json. */
    public val onChrome: Color,
    /** Token `pill-hi`; its usage note is in reference/design-system/tokens.json. */
    public val pillHi: Color,
    /** Token `pill-lo`; its usage note is in reference/design-system/tokens.json. */
    public val pillLo: Color,
    /** Token `on-pill`; its usage note is in reference/design-system/tokens.json. */
    public val onPill: Color,
    /** Token `accent-hi`; its usage note is in reference/design-system/tokens.json. */
    public val accentHi: Color,
    /** Token `accent`; its usage note is in reference/design-system/tokens.json. */
    public val accent: Color,
    /** Token `accent-lo`; its usage note is in reference/design-system/tokens.json. */
    public val accentLo: Color,
    /** Token `on-accent`; its usage note is in reference/design-system/tokens.json. */
    public val onAccent: Color,
    /** Token `accent-rim`; its usage note is in reference/design-system/tokens.json. */
    public val accentRim: Color,
    /** Token `accent-ink`; its usage note is in reference/design-system/tokens.json. */
    public val accentInk: Color,
    /** Token `select`; its usage note is in reference/design-system/tokens.json. */
    public val select: Color,
    /** Token `on-select`; its usage note is in reference/design-system/tokens.json. */
    public val onSelect: Color,
    /** Token `focus`; its usage note is in reference/design-system/tokens.json. */
    public val focus: Color,
    /** Token `success`; its usage note is in reference/design-system/tokens.json. */
    public val success: Color,
    /** Token `warning`; its usage note is in reference/design-system/tokens.json. */
    public val warning: Color,
    /** Token `danger`; its usage note is in reference/design-system/tokens.json. */
    public val danger: Color,
    /** Token `lcd`; its usage note is in reference/design-system/tokens.json. */
    public val lcd: Color,
    /** Token `lcd-ink`; its usage note is in reference/design-system/tokens.json. */
    public val lcdInk: Color,
    /** Token `lcd-dim`; its usage note is in reference/design-system/tokens.json. */
    public val lcdDim: Color,
    /** Token `lcd-ghost`; its usage note is in reference/design-system/tokens.json. */
    public val lcdGhost: Color,
    /** Token `meter-low`; its usage note is in reference/design-system/tokens.json. */
    public val meterLow: Color,
    /** Token `meter-mid`; its usage note is in reference/design-system/tokens.json. */
    public val meterMid: Color,
    /** Token `meter-peak`; its usage note is in reference/design-system/tokens.json. */
    public val meterPeak: Color,
    /** Token `grain`; its usage note is in reference/design-system/tokens.json. */
    public val grain: Color,
    /** Token `bezel-weave`; its usage note is in reference/design-system/tokens.json. */
    public val bezelWeave: Color,
    /** Token `bezel-speckle`; its usage note is in reference/design-system/tokens.json. */
    public val bezelSpeckle: Color,
    /** Token `balloon`; its usage note is in reference/design-system/tokens.json. */
    public val balloon: Color,
    /** Token `on-balloon`; its usage note is in reference/design-system/tokens.json. */
    public val onBalloon: Color,
    /** Token `balloon-mark`; its usage note is in reference/design-system/tokens.json. */
    public val balloonMark: Color,
) {
    public companion object {
        /** The Toxic skin. */
        public val Toxic: OldgeColors =
            OldgeColors(
                bodyHi = Color(0xFF17260F),
                ground = Color(0xFF050805),
                glow = Color(0x298CFF28),
                surface = Color(0xFF101A0C),
                surface2 = Color(0xFF172410),
                well = Color(0xFF030502),
                ink = Color(0xFFECF8E0),
                inkMuted = Color(0xFFA8BD96),
                line = Color(0xFF2A3A20),
                edge = Color(0xFF6F8C58),
                gloss = Color(0x33FFFFFF),
                bezelHi = Color(0xFF3B4637),
                bezel = Color(0xFF1D241B),
                bezelLo = Color(0xFF090C08),
                onBezel = Color(0xFFEEF8E6),
                chromeHi = Color(0xFFEEF4EA),
                chromeLo = Color(0xFF9FAD98),
                onChrome = Color(0xFF0F160B),
                pillHi = Color(0xFFE9F7DC),
                pillLo = Color(0xFFB6D19E),
                onPill = Color(0xFF1F3A08),
                accentHi = Color(0xFFD2FF6E),
                accent = Color(0xFFA4FF1F),
                accentLo = Color(0xFF72D400),
                onAccent = Color(0xFF0B1400),
                accentRim = Color(0xFF9FAD98),
                accentInk = Color(0xFFA8FF3A),
                select = Color(0xFF2F5A0A),
                onSelect = Color(0xFFF2FFE6),
                focus = Color(0xFFFFE14D),
                success = Color(0xFF6FE8A8),
                warning = Color(0xFFFFC94D),
                danger = Color(0xFFFF7B6E),
                lcd = Color(0xFF030A03),
                lcdInk = Color(0xFF8DFF3A),
                lcdDim = Color(0xFF4F9A1F),
                lcdGhost = Color(0xFF0F2A0A),
                meterLow = Color(0xFF8DFF3A),
                meterMid = Color(0xFFFFD23A),
                meterPeak = Color(0xFFFF4D2E),
                grain = Color(0x12BEFF8C),
                bezelWeave = Color(0x0DFFFFFF),
                bezelSpeckle = Color(0x00000000),
                balloon = Color(0xFFFFFFE1),
                onBalloon = Color(0xFF1A1A1A),
                balloonMark = Color(0xFF1F63D6),
            )

        /** The Media skin. */
        public val Media: OldgeColors =
            OldgeColors(
                bodyHi = Color(0xFF1C4A9E),
                ground = Color(0xFF061A4A),
                glow = Color(0x3896D7FF),
                surface = Color(0xFF0C2A66),
                surface2 = Color(0xFF12357A),
                well = Color(0xFF04123A),
                ink = Color(0xFFF3F8FF),
                inkMuted = Color(0xFFB6C9EC),
                line = Color(0xFF25488F),
                edge = Color(0xFF7D9FD8),
                gloss = Color(0x42FFFFFF),
                bezelHi = Color(0xFF3A70D0),
                bezel = Color(0xFF1B4AA8),
                bezelLo = Color(0xFF0A2466),
                onBezel = Color(0xFFFFFFFF),
                chromeHi = Color(0xFFF3F7FF),
                chromeLo = Color(0xFFA8B8D8),
                onChrome = Color(0xFF0B1733),
                pillHi = Color(0xFFE9F1FF),
                pillLo = Color(0xFFB2C7EE),
                onPill = Color(0xFF0D2F75),
                accentHi = Color(0xFFD2FF6E),
                accent = Color(0xFFA4FF1F),
                accentLo = Color(0xFF72D400),
                onAccent = Color(0xFF0B1400),
                accentRim = Color(0xFFA8B8D8),
                accentInk = Color(0xFFB8FF5C),
                select = Color(0xFF2D64C8),
                onSelect = Color(0xFFFFFFFF),
                focus = Color(0xFFFFE14D),
                success = Color(0xFF7EF0B0),
                warning = Color(0xFFFFD166),
                danger = Color(0xFFFFACA3),
                lcd = Color(0xFF041330),
                lcdInk = Color(0xFF9FE0FF),
                lcdDim = Color(0xFF5F95C8),
                lcdGhost = Color(0xFF0F2750),
                meterLow = Color(0xFF5EE07A),
                meterMid = Color(0xFFFFD23A),
                meterPeak = Color(0xFFFF4D2E),
                grain = Color(0x0DFFFFFF),
                bezelWeave = Color(0x00000000),
                bezelSpeckle = Color(0x00000000),
                balloon = Color(0xFFFFFFE1),
                onBalloon = Color(0xFF1A1A1A),
                balloonMark = Color(0xFF1F63D6),
            )

        /** The Crystal skin. */
        public val Crystal: OldgeColors =
            OldgeColors(
                bodyHi = Color(0xFFF8FCF4),
                ground = Color(0xFFE2EBDD),
                glow = Color(0x73AAFF50),
                surface = Color(0xFFFFFFFF),
                surface2 = Color(0xFFF0F6EC),
                well = Color(0xFFFFFFFF),
                ink = Color(0xFF0F1A0B),
                inkMuted = Color(0xFF4C5C45),
                line = Color(0xFFCFDCC8),
                edge = Color(0xFF5D7A50),
                gloss = Color(0x8CFFFFFF),
                bezelHi = Color(0xFF5B6A56),
                bezel = Color(0xFF2E3A2A),
                bezelLo = Color(0xFF131B11),
                onBezel = Color(0xFFF4FAEF),
                chromeHi = Color(0xFFFFFFFF),
                chromeLo = Color(0xFFC9D3C3),
                onChrome = Color(0xFF11180E),
                pillHi = Color(0xFFFFFFFF),
                pillLo = Color(0xFFCFE8B8),
                onPill = Color(0xFF234508),
                accentHi = Color(0xFFB8F53A),
                accent = Color(0xFF8FE010),
                accentLo = Color(0xFF5AA800),
                onAccent = Color(0xFF0B1400),
                accentRim = Color(0xFF3B7A00),
                accentInk = Color(0xFF357000),
                select = Color(0xFF3B7A00),
                onSelect = Color(0xFFFFFFFF),
                focus = Color(0xFFB85600),
                success = Color(0xFF1B6E42),
                warning = Color(0xFF8A5A00),
                danger = Color(0xFFC42B1C),
                lcd = Color(0xFFC3D6A0),
                lcdInk = Color(0xFF1F2A12),
                lcdDim = Color(0xFF46552C),
                lcdGhost = Color(0xFFAFC28A),
                meterLow = Color(0xFF2F6E14),
                meterMid = Color(0xFF7A5C00),
                meterPeak = Color(0xFFB3200E),
                grain = Color(0x121E3C14),
                bezelWeave = Color(0x00000000),
                bezelSpeckle = Color(0x38FFFFFF),
                balloon = Color(0xFFFFFFE1),
                onBalloon = Color(0xFF1A1A1A),
                balloonMark = Color(0xFF1F63D6),
            )
    }
}

/** One layer of a CSS box-shadow: `inset` draws inside the shape's outline, a drop shadow outside it. */
@Immutable
public data class OldgeShadow(
    public val inset: Boolean,
    public val offsetX: Dp,
    public val offsetY: Dp,
    public val blur: Dp,
    public val spread: Dp,
    public val color: Color,
)

/** The design system's shadow tokens for one skin; each is a list of layers, empty for `none`. */
@Immutable
public class OldgeShadows(
    /** Token `shadow-raised`; its usage note is in reference/design-system/tokens.json. */
    public val raised: List<OldgeShadow>,
    /** Token `shadow-sunken`; its usage note is in reference/design-system/tokens.json. */
    public val sunken: List<OldgeShadow>,
    /** Token `shadow-bezel`; its usage note is in reference/design-system/tokens.json. */
    public val bezel: List<OldgeShadow>,
    /** Token `shadow-orb`; its usage note is in reference/design-system/tokens.json. */
    public val orb: List<OldgeShadow>,
    /** Token `shadow-window`; its usage note is in reference/design-system/tokens.json. */
    public val window: List<OldgeShadow>,
    /** Token `shadow-balloon`; its usage note is in reference/design-system/tokens.json. */
    public val balloon: List<OldgeShadow>,
    /** Token `shadow-lcd-glow`; its usage note is in reference/design-system/tokens.json. */
    public val lcdGlow: List<OldgeShadow>,
) {
    public companion object {
        /** The Toxic skin. */
        public val Toxic: OldgeShadows =
            OldgeShadows(
                raised =
                    listOf(
                        OldgeShadow(inset = true, offsetX = 1.dp, offsetY = 1.dp, blur = 0.dp, spread = 0.dp, color = Color(0x29FFFFFF)),
                        OldgeShadow(inset = true, offsetX = -1.dp, offsetY = -1.dp, blur = 0.dp, spread = 0.dp, color = Color(0x8C000000)),
                    ),
                sunken =
                    listOf(
                        OldgeShadow(inset = true, offsetX = 1.dp, offsetY = 1.dp, blur = 0.dp, spread = 0.dp, color = Color(0x99000000)),
                        OldgeShadow(inset = true, offsetX = -1.dp, offsetY = -1.dp, blur = 0.dp, spread = 0.dp, color = Color(0x1AFFFFFF)),
                    ),
                bezel =
                    listOf(
                        OldgeShadow(inset = true, offsetX = 0.dp, offsetY = 1.dp, blur = 0.dp, spread = 0.dp, color = Color(0x59FFFFFF)),
                        OldgeShadow(inset = true, offsetX = 0.dp, offsetY = -1.dp, blur = 0.dp, spread = 0.dp, color = Color(0x73000000)),
                    ),
                orb =
                    listOf(
                        OldgeShadow(inset = false, offsetX = 0.dp, offsetY = 2.dp, blur = 4.dp, spread = 0.dp, color = Color(0x99000000)),
                    ),
                window =
                    listOf(
                        OldgeShadow(inset = false, offsetX = 0.dp, offsetY = 10.dp, blur = 28.dp, spread = 0.dp, color = Color(0xB3000000)),
                    ),
                balloon =
                    listOf(
                        OldgeShadow(inset = false, offsetX = 2.dp, offsetY = 3.dp, blur = 0.dp, spread = 0.dp, color = Color(0x59000000)),
                    ),
                lcdGlow =
                    listOf(
                        OldgeShadow(inset = false, offsetX = 0.dp, offsetY = 0.dp, blur = 6.dp, spread = 0.dp, color = Color(0x998DFF3A)),
                    ),
            )

        /** The Media skin. */
        public val Media: OldgeShadows =
            OldgeShadows(
                raised =
                    listOf(
                        OldgeShadow(inset = true, offsetX = 1.dp, offsetY = 1.dp, blur = 0.dp, spread = 0.dp, color = Color(0x29FFFFFF)),
                        OldgeShadow(inset = true, offsetX = -1.dp, offsetY = -1.dp, blur = 0.dp, spread = 0.dp, color = Color(0x8C000000)),
                    ),
                sunken =
                    listOf(
                        OldgeShadow(inset = true, offsetX = 1.dp, offsetY = 1.dp, blur = 0.dp, spread = 0.dp, color = Color(0x99000000)),
                        OldgeShadow(inset = true, offsetX = -1.dp, offsetY = -1.dp, blur = 0.dp, spread = 0.dp, color = Color(0x1AFFFFFF)),
                    ),
                bezel =
                    listOf(
                        OldgeShadow(inset = true, offsetX = 0.dp, offsetY = 1.dp, blur = 0.dp, spread = 0.dp, color = Color(0x59FFFFFF)),
                        OldgeShadow(inset = true, offsetX = 0.dp, offsetY = -1.dp, blur = 0.dp, spread = 0.dp, color = Color(0x73000000)),
                    ),
                orb =
                    listOf(
                        OldgeShadow(inset = false, offsetX = 0.dp, offsetY = 2.dp, blur = 5.dp, spread = 0.dp, color = Color(0x8C000A28)),
                    ),
                window =
                    listOf(
                        OldgeShadow(inset = false, offsetX = 0.dp, offsetY = 10.dp, blur = 28.dp, spread = 0.dp, color = Color(0x99000828)),
                    ),
                balloon =
                    listOf(
                        OldgeShadow(inset = false, offsetX = 2.dp, offsetY = 3.dp, blur = 0.dp, spread = 0.dp, color = Color(0x59000000)),
                    ),
                lcdGlow =
                    listOf(
                        OldgeShadow(inset = false, offsetX = 0.dp, offsetY = 0.dp, blur = 6.dp, spread = 0.dp, color = Color(0x999FE0FF)),
                    ),
            )

        /** The Crystal skin. */
        public val Crystal: OldgeShadows =
            OldgeShadows(
                raised =
                    listOf(
                        OldgeShadow(inset = true, offsetX = 1.dp, offsetY = 1.dp, blur = 0.dp, spread = 0.dp, color = Color(0xFFFFFFFF)),
                        OldgeShadow(inset = true, offsetX = -1.dp, offsetY = -1.dp, blur = 0.dp, spread = 0.dp, color = Color(0xFFB9C6B2)),
                    ),
                sunken =
                    listOf(
                        OldgeShadow(inset = true, offsetX = 1.dp, offsetY = 1.dp, blur = 0.dp, spread = 0.dp, color = Color(0xFFB9C6B2)),
                        OldgeShadow(inset = true, offsetX = -1.dp, offsetY = -1.dp, blur = 0.dp, spread = 0.dp, color = Color(0xFFFFFFFF)),
                    ),
                bezel =
                    listOf(
                        OldgeShadow(inset = true, offsetX = 0.dp, offsetY = 1.dp, blur = 0.dp, spread = 0.dp, color = Color(0x59FFFFFF)),
                        OldgeShadow(inset = true, offsetX = 0.dp, offsetY = -1.dp, blur = 0.dp, spread = 0.dp, color = Color(0x73000000)),
                    ),
                orb =
                    listOf(
                        OldgeShadow(inset = false, offsetX = 0.dp, offsetY = 1.dp, blur = 3.dp, spread = 0.dp, color = Color(0x47000000)),
                    ),
                window =
                    listOf(
                        OldgeShadow(inset = false, offsetX = 0.dp, offsetY = 6.dp, blur = 16.dp, spread = 0.dp, color = Color(0x40000000)),
                    ),
                balloon =
                    listOf(
                        OldgeShadow(inset = false, offsetX = 2.dp, offsetY = 3.dp, blur = 0.dp, spread = 0.dp, color = Color(0x59000000)),
                    ),
                lcdGlow = emptyList(),
            )
    }
}

/** The 4 px spacing scale and the minimum touch target. */
public object OldgeSpacing {
    /** Token `space-1`; its usage note is in reference/design-system/tokens.json. */
    public val space1: Dp = 4.dp

    /** Token `space-2`; its usage note is in reference/design-system/tokens.json. */
    public val space2: Dp = 8.dp

    /** Token `space-3`; its usage note is in reference/design-system/tokens.json. */
    public val space3: Dp = 12.dp

    /** Token `space-4`; its usage note is in reference/design-system/tokens.json. */
    public val space4: Dp = 16.dp

    /** Token `space-5`; its usage note is in reference/design-system/tokens.json. */
    public val space5: Dp = 24.dp

    /** Token `space-6`; its usage note is in reference/design-system/tokens.json. */
    public val space6: Dp = 32.dp

    /** Token `hit-min`; its usage note is in reference/design-system/tokens.json. */
    public val hitMin: Dp = 44.dp
}

/** Corner radii; `pill` is 999 px, which is fully round at any size the design uses. */
public object OldgeRadii {
    /** Token `radius-xs`; its usage note is in reference/design-system/tokens.json. */
    public val xs: Dp = 2.dp

    /** Token `radius-sm`; its usage note is in reference/design-system/tokens.json. */
    public val sm: Dp = 4.dp

    /** Token `radius-md`; its usage note is in reference/design-system/tokens.json. */
    public val md: Dp = 8.dp

    /** Token `radius-lg`; its usage note is in reference/design-system/tokens.json. */
    public val lg: Dp = 12.dp

    /** Token `radius-xl`; its usage note is in reference/design-system/tokens.json. */
    public val xl: Dp = 20.dp

    /** Token `radius-pill`; its usage note is in reference/design-system/tokens.json. */
    public val pill: Dp = 999.dp
}

/** Durations in milliseconds. Under reduced motion the theme uses none of them (research D7). */
public object OldgeDurations {
    /** Token `dur-instant`; its usage note is in reference/design-system/tokens.json. */
    public val instant: Int = 90

    /** Token `dur-fast`; its usage note is in reference/design-system/tokens.json. */
    public val fast: Int = 160

    /** Token `dur-base`; its usage note is in reference/design-system/tokens.json. */
    public val base: Int = 260

    /** Token `dur-slow`; its usage note is in reference/design-system/tokens.json. */
    public val slow: Int = 420

    /** Token `dur-press`; its usage note is in reference/design-system/tokens.json. */
    public val press: Int = 600

    /** Token `dur-loop`; its usage note is in reference/design-system/tokens.json. */
    public val loop: Int = 1200
}

/** The design system's four curves. */
public object OldgeEasings {
    /** Token `ease-spring`; its usage note is in reference/design-system/tokens.json. */
    public val spring: Easing = CubicBezierEasing(0.34f, 1.56f, 0.64f, 1f)

    /** Token `ease-bounce`; its usage note is in reference/design-system/tokens.json. */
    public val bounce: Easing = CubicBezierEasing(0.68f, -0.6f, 0.32f, 1.6f)

    /** Token `ease-out`; its usage note is in reference/design-system/tokens.json. */
    public val out: Easing = CubicBezierEasing(0.2f, 0.8f, 0.2f, 1f)

    /** Token `ease-linear`; its usage note is in reference/design-system/tokens.json. */
    public val linear: Easing = LinearEasing
}

/** The design system's font families (research D6 says which faces each one bundles). */
public enum class OldgeFontFamilyKey { Ui, Title, Lcd, Pixel }

/** A type style as the design system states it: rem for size and line height, em for spacing. */
@Immutable
public data class OldgeTypeStyle(
    public val family: OldgeFontFamilyKey,
    public val sizeRem: Float,
    public val lineHeightRem: Float,
    public val weight: Int,
    public val letterSpacingEm: Float,
)

/** The design system's type styles. */
public object OldgeTypeStyles {
    /** Token `display`; its usage note is in reference/design-system/tokens.json. */
    public val display: OldgeTypeStyle =
        OldgeTypeStyle(OldgeFontFamilyKey.Title, 1.75f, 2f, 700, 0f)

    /** Token `heading`; its usage note is in reference/design-system/tokens.json. */
    public val heading: OldgeTypeStyle =
        OldgeTypeStyle(OldgeFontFamilyKey.Title, 1.25f, 1.5f, 700, 0f)

    /** Token `title`; its usage note is in reference/design-system/tokens.json. */
    public val title: OldgeTypeStyle =
        OldgeTypeStyle(OldgeFontFamilyKey.Title, 1.0625f, 1.375f, 700, 0f)

    /** Token `body`; its usage note is in reference/design-system/tokens.json. */
    public val body: OldgeTypeStyle =
        OldgeTypeStyle(OldgeFontFamilyKey.Ui, 0.9375f, 1.25f, 400, 0f)

    /** Token `body-strong`; its usage note is in reference/design-system/tokens.json. */
    public val bodyStrong: OldgeTypeStyle =
        OldgeTypeStyle(OldgeFontFamilyKey.Ui, 0.9375f, 1.25f, 700, 0f)

    /** Token `button`; its usage note is in reference/design-system/tokens.json. */
    public val button: OldgeTypeStyle =
        OldgeTypeStyle(OldgeFontFamilyKey.Ui, 0.9375f, 1.25f, 700, 0f)

    /** Token `label`; its usage note is in reference/design-system/tokens.json. */
    public val label: OldgeTypeStyle =
        OldgeTypeStyle(OldgeFontFamilyKey.Ui, 0.8125f, 1f, 700, 0f)

    /** Token `caption`; its usage note is in reference/design-system/tokens.json. */
    public val caption: OldgeTypeStyle =
        OldgeTypeStyle(OldgeFontFamilyKey.Ui, 0.75f, 1f, 400, 0f)

    /** Token `readout`; its usage note is in reference/design-system/tokens.json. */
    public val readout: OldgeTypeStyle =
        OldgeTypeStyle(OldgeFontFamilyKey.Lcd, 2.125f, 2.125f, 400, 0.04f)

    /** Token `readout-sm`; its usage note is in reference/design-system/tokens.json. */
    public val readoutSm: OldgeTypeStyle =
        OldgeTypeStyle(OldgeFontFamilyKey.Lcd, 1f, 1.25f, 400, 0f)

    /** Token `pixel-tag`; its usage note is in reference/design-system/tokens.json. */
    public val pixelTag: OldgeTypeStyle =
        OldgeTypeStyle(OldgeFontFamilyKey.Pixel, 0.625f, 0.75f, 400, 0.06f)
}

/**
 * Every generated value by its design-system token name, per skin where it varies. It points at
 * the properties above rather than restating them, so a test that compares it with tokens.json
 * tests the properties.
 */
internal object OldgeTokenIndex {
    val skins: List<String> = listOf("toxic", "media", "crystal")

    fun colors(skin: String): Map<String, Color> {
        val c = when (skin) {
            "toxic" -> OldgeColors.Toxic
            "media" -> OldgeColors.Media
            "crystal" -> OldgeColors.Crystal
            else -> error("no skin $skin")
        }
        return mapOf(
            "body-hi" to c.bodyHi,
            "ground" to c.ground,
            "glow" to c.glow,
            "surface" to c.surface,
            "surface-2" to c.surface2,
            "well" to c.well,
            "ink" to c.ink,
            "ink-muted" to c.inkMuted,
            "line" to c.line,
            "edge" to c.edge,
            "gloss" to c.gloss,
            "bezel-hi" to c.bezelHi,
            "bezel" to c.bezel,
            "bezel-lo" to c.bezelLo,
            "on-bezel" to c.onBezel,
            "chrome-hi" to c.chromeHi,
            "chrome-lo" to c.chromeLo,
            "on-chrome" to c.onChrome,
            "pill-hi" to c.pillHi,
            "pill-lo" to c.pillLo,
            "on-pill" to c.onPill,
            "accent-hi" to c.accentHi,
            "accent" to c.accent,
            "accent-lo" to c.accentLo,
            "on-accent" to c.onAccent,
            "accent-rim" to c.accentRim,
            "accent-ink" to c.accentInk,
            "select" to c.select,
            "on-select" to c.onSelect,
            "focus" to c.focus,
            "success" to c.success,
            "warning" to c.warning,
            "danger" to c.danger,
            "lcd" to c.lcd,
            "lcd-ink" to c.lcdInk,
            "lcd-dim" to c.lcdDim,
            "lcd-ghost" to c.lcdGhost,
            "meter-low" to c.meterLow,
            "meter-mid" to c.meterMid,
            "meter-peak" to c.meterPeak,
            "grain" to c.grain,
            "bezel-weave" to c.bezelWeave,
            "bezel-speckle" to c.bezelSpeckle,
            "balloon" to c.balloon,
            "on-balloon" to c.onBalloon,
            "balloon-mark" to c.balloonMark,
        )
    }

    fun shadows(skin: String): Map<String, List<OldgeShadow>> {
        val s = when (skin) {
            "toxic" -> OldgeShadows.Toxic
            "media" -> OldgeShadows.Media
            "crystal" -> OldgeShadows.Crystal
            else -> error("no skin $skin")
        }
        return mapOf(
            "shadow-raised" to s.raised,
            "shadow-sunken" to s.sunken,
            "shadow-bezel" to s.bezel,
            "shadow-orb" to s.orb,
            "shadow-window" to s.window,
            "shadow-balloon" to s.balloon,
            "shadow-lcd-glow" to s.lcdGlow,
        )
    }

    val spacing: Map<String, Dp> =
        mapOf(
            "space-1" to OldgeSpacing.space1,
            "space-2" to OldgeSpacing.space2,
            "space-3" to OldgeSpacing.space3,
            "space-4" to OldgeSpacing.space4,
            "space-5" to OldgeSpacing.space5,
            "space-6" to OldgeSpacing.space6,
            "hit-min" to OldgeSpacing.hitMin,
        )

    val radius: Map<String, Dp> =
        mapOf(
            "radius-xs" to OldgeRadii.xs,
            "radius-sm" to OldgeRadii.sm,
            "radius-md" to OldgeRadii.md,
            "radius-lg" to OldgeRadii.lg,
            "radius-xl" to OldgeRadii.xl,
            "radius-pill" to OldgeRadii.pill,
        )

    val duration: Map<String, Int> =
        mapOf(
            "dur-instant" to OldgeDurations.instant,
            "dur-fast" to OldgeDurations.fast,
            "dur-base" to OldgeDurations.base,
            "dur-slow" to OldgeDurations.slow,
            "dur-press" to OldgeDurations.press,
            "dur-loop" to OldgeDurations.loop,
        )

    val easing: Map<String, Easing> =
        mapOf(
            "ease-spring" to OldgeEasings.spring,
            "ease-bounce" to OldgeEasings.bounce,
            "ease-out" to OldgeEasings.out,
            "ease-linear" to OldgeEasings.linear,
        )

    val type: Map<String, OldgeTypeStyle> =
        mapOf(
            "display" to OldgeTypeStyles.display,
            "heading" to OldgeTypeStyles.heading,
            "title" to OldgeTypeStyles.title,
            "body" to OldgeTypeStyles.body,
            "body-strong" to OldgeTypeStyles.bodyStrong,
            "button" to OldgeTypeStyles.button,
            "label" to OldgeTypeStyles.label,
            "caption" to OldgeTypeStyles.caption,
            "readout" to OldgeTypeStyles.readout,
            "readout-sm" to OldgeTypeStyles.readoutSm,
            "pixel-tag" to OldgeTypeStyles.pixelTag,
        )
}
