// GENERATED by scripts/fonts/generate_coverage.py from the files in composeResources/font.
// Do not edit: FontCoverageTest re-derives every range from the font files and fails on a
// difference.
package io.github.youndie.oldge.type

/** Inclusive code point ranges, as `[first0, last0, first1, last1, ...]`, per face. */
internal object FontCoverage {
    /** `share_tech_mono.ttf`: 50 ranges. */
    val shareTechMono: IntArray =
        intArrayOf(
            0x0020,
            0x007E,
            0x00A0,
            0x00FF,
            0x0131,
            0x0131,
            0x0141,
            0x0142,
            0x0152,
            0x0153,
            0x0160,
            0x0161,
            0x0178,
            0x0178,
            0x017D,
            0x017E,
            0x0192,
            0x0192,
            0x02C6,
            0x02C7,
            0x02C9,
            0x02C9,
            0x02D8,
            0x02DD,
            0x03BC,
            0x03BC,
            0x03C0,
            0x03C0,
            0x2013,
            0x2014,
            0x2018,
            0x201A,
            0x201C,
            0x201E,
            0x2020,
            0x2022,
            0x2026,
            0x2026,
            0x2030,
            0x2030,
            0x2039,
            0x203A,
            0x2044,
            0x2044,
            0x20AC,
            0x20AC,
            0x2122,
            0x2122,
            0x2126,
            0x2126,
            0x2202,
            0x2202,
            0x2206,
            0x2206,
            0x220F,
            0x220F,
            0x2211,
            0x2212,
            0x2215,
            0x2215,
            0x2219,
            0x221A,
            0x221E,
            0x221E,
            0x2224,
            0x2224,
            0x2227,
            0x2227,
            0x222B,
            0x222B,
            0x2248,
            0x2248,
            0x2260,
            0x2260,
            0x2264,
            0x2265,
            0x22C5,
            0x22C5,
            0x25AF,
            0x25AF,
            0x25CA,
            0x25CA,
            0x2620,
            0x2620,
            0x263A,
            0x263C,
            0x2640,
            0x2640,
            0x2642,
            0x2642,
            0x2660,
            0x2660,
            0x2663,
            0x2663,
            0x2665,
            0x2666,
            0x266A,
            0x266B,
            0xFB01,
            0xFB02,
        )

    /** `silkscreen.ttf`: 21 ranges. */
    val silkscreen: IntArray =
        intArrayOf(
            0x0020,
            0x007E,
            0x00A0,
            0x00FF,
            0x0152,
            0x0153,
            0x0160,
            0x0161,
            0x0178,
            0x0178,
            0x017D,
            0x017E,
            0x0192,
            0x0192,
            0x02C6,
            0x02C6,
            0x02DC,
            0x02DC,
            0x0300,
            0x0304,
            0x0308,
            0x0308,
            0x0327,
            0x0327,
            0x2013,
            0x2014,
            0x2018,
            0x201A,
            0x201C,
            0x201E,
            0x2020,
            0x2022,
            0x2026,
            0x2026,
            0x2030,
            0x2030,
            0x2039,
            0x203A,
            0x20AC,
            0x20AC,
            0x2122,
            0x2122,
        )
}

/** Vertical metrics in font units, as a browser reads them (OS/2 typo with USE_TYPO_METRICS, else hhea). */
internal class FontVerticalMetrics(
    val ascent: Int,
    val descent: Int,
    val unitsPerEm: Int,
)

/** Every bundled face's vertical metrics. */
internal object BundledFontMetrics {
    /** `dejavu_sans_condensed.ttf`. */
    val dejavuSansCondensed: FontVerticalMetrics = FontVerticalMetrics(ascent = 1901, descent = 483, unitsPerEm = 2048)

    /** `dejavu_sans_condensed_bold.ttf`. */
    val dejavuSansCondensedBold: FontVerticalMetrics =
        FontVerticalMetrics(ascent = 1901, descent = 483, unitsPerEm = 2048)

    /** `fira_sans_bold.ttf`. */
    val firaSansBold: FontVerticalMetrics = FontVerticalMetrics(ascent = 935, descent = 265, unitsPerEm = 1000)

    /** `share_tech_mono.ttf`. */
    val shareTechMono: FontVerticalMetrics = FontVerticalMetrics(ascent = 885, descent = 242, unitsPerEm = 1000)

    /** `pt_mono.ttf`. */
    val ptMono: FontVerticalMetrics = FontVerticalMetrics(ascent = 885, descent = 235, unitsPerEm = 1000)

    /** `silkscreen.ttf`. */
    val silkscreen: FontVerticalMetrics = FontVerticalMetrics(ascent = 1030, descent = 250, unitsPerEm = 1000)

    /** `tiny5.ttf`. */
    val tiny5: FontVerticalMetrics = FontVerticalMetrics(ascent = 896, descent = 256, unitsPerEm = 1024)
}
