#!/usr/bin/env python3
"""
The component catalogue (B-42): which composable is the design system's which component, in which
file, and what shows it.

    python3 scripts/component_catalog.py            # rewrite the generated part of docs/components.md
    python3 scripts/component_catalog.py --check    # fail if it is stale, or names what is not there

WHY GENERATED. A hand-written catalogue of fifty components is wrong within a sprint, and wrong in
the direction that costs most: it keeps listing what was renamed and stops listing what was added,
and both look like a correct document. So the table is derived from what cannot lie about it:

  * the design system's own list of components, `index.d.ts` (51 exports, research §1.1);
  * the public composables in oldge-core's sources;
  * the parity references (`design/manifest.json`) and the goldens, which viddik's registry and
    `ScreenshotSuiteTest` hold to the fixtures, so that a golden here stands for a running instance;
  * the pages' screens in `sample`.

WHAT FAILS THE CHECK, IN BOTH DIRECTIONS.

  * An export with no composable: the library does not have a component the design system has.
  * A name in `ALSO` or `INSTEAD` that is not a public composable: the map below outlived a rename.
  * A public composable in neither table: it would be invisible to the reader this file is for.
  * A page with no screen in `sample`.
  * The generated part differing from what is on disk: somebody edited it by hand, or the sources
    moved on without it.

The one hand-kept part is the map below, and every name in it is checked against the sources.
"""
import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DS = ROOT / "reference/design-system/components"
CORE = ROOT / "oldge-core/src/commonMain/kotlin"
SAMPLE = ROOT / "sample/src/commonMain/kotlin"
GOLDENS = ROOT / "oldge-core/src/desktopTest/snapshots"
MANIFEST = GOLDENS / "design/manifest.json"
CATALOG = ROOT / "docs/components.md"

BEGIN = "<!-- BEGIN CATALOG - generated by scripts/component_catalog.py, do not edit by hand -->"
END = "<!-- END CATALOG -->"

# An export whose composables are not `Oldge<Name>`: the design system's one component that the
# library splits into several, as Material does.
INSTEAD = {
    "Chip": ["OldgeAssistChip", "OldgeFilterChip", "OldgeInputChip"],
    "ListSection": ["oldgeListSections", "OldgeListSectionHeader"],
}
# Public forms of an export beyond its `Oldge<Name>`.
ALSO = {
    "Button": ["OldgeIconButton"],
    "Fab": ["OldgeExtendedFab", "OldgeFabDock"],
    "PullRefresh": ["OldgeLazyPullRefresh"],
}

DECLARATION = re.compile(r"^public fun (?:<[^>]*>\s*)?(?:[A-Za-z_][\w.]*\.)?(?P<name>[A-Za-z_]\w*)\s*\(", re.M)
SKINS = ["Toxic", "Media", "Crystal"]


def kdoc_first_sentence(text, start):
    """The first sentence of the KDoc above the declaration at `start`, or an empty string."""
    head = text[:start].rstrip()
    while head.split("\n")[-1].lstrip().startswith("@"):
        head = "\n".join(head.split("\n")[:-1]).rstrip()
    if not head.endswith("*/"):
        return ""
    open_at = head.rfind("/**")
    if open_at < 0:
        return ""
    body = " ".join(
        re.sub(r"^\s*\*\s?", "", line).strip()
        for line in head[open_at + 3 : -2].split("\n")
    ).strip()
    # Up to the first full stop that ends a sentence, or the first colon or dash that opens a list.
    match = re.match(r"(.+?[.:])(\s|$)", body)
    sentence = (match.group(1) if match else body).rstrip(":")
    return re.sub(r"\s+", " ", sentence).replace("|", "\\|")


def public_composables(tree):
    """Every `public fun` in a source tree: name → (path relative to the root, first KDoc sentence)."""
    found = {}
    for path in sorted(tree.rglob("*.kt")):
        text = path.read_text(encoding="utf-8")
        for m in DECLARATION.finditer(text):
            found.setdefault(m.group("name"), (path.relative_to(ROOT).as_posix(), kdoc_first_sentence(text, m.start())))
    return found


def exports():
    text = (DS / "index.d.ts").read_text(encoding="utf-8")
    return sorted(set(re.findall(r"export (?:declare )?(?:function|const) ([A-Za-z]+)", text)))


def card(name):
    """The preview's `@dsCard` line: its group, and whether it is a page."""
    preview = DS / name / "preview.html"
    if not preview.is_file():
        return None, False
    first = preview.read_text(encoding="utf-8").split("\n")[0]
    group = re.search(r'group="([^"]+)"', first)
    return (group.group(1) if group else None), bool(re.search(r"\bpage\b", first))


def reference_stems(name):
    import json

    refs = json.loads(MANIFEST.read_text(encoding="utf-8"))["references"]
    skins = [s for s in SKINS if f"{name}_{s}" in refs]
    return f"`{name}_{{{','.join(skins)}}}`" if skins else "—"


def golden_groups(name):
    """The fixture groups of a component: its own and its `States`, as their golden stems name them."""
    stems = {p.stem for p in GOLDENS.glob("*.png")}
    groups = []
    for group in (name, f"{name}States"):
        if any(s.startswith(group + "_") for s in stems):
            groups.append(f"`{group}`")
    return ", ".join(groups) or "—"


def generate():
    core = public_composables(CORE)
    screens = public_composables(SAMPLE)
    errors = []
    rows = []
    claimed = set()
    for name in exports():
        names = INSTEAD.get(name, [f"Oldge{name}"]) + ALSO.get(name, [])
        missing = [n for n in names if n not in core]
        if missing:
            errors.append(f"{name}: no public composable {', '.join(missing)}")
            continue
        claimed.update(names)
        group, _ = card(name)
        path, summary = core[names[0]]
        readme = DS / name / "README.md"
        rows.append(
            "| {name} | {composables} | [{file}](../{path}) | {group} | {refs} | {goldens} | {readme} | {summary} |".format(
                name=name,
                composables=", ".join(f"`{n}`" for n in names),
                file=Path(path).name,
                path=path,
                group=group or "— (no preview)",
                refs=reference_stems(name),
                goldens=golden_groups(name),
                readme=f"[README](../{readme.relative_to(ROOT).as_posix()})" if readme.is_file() else "—",
                summary=summary,
            )
        )
    beyond = [n for n in sorted(core) if n not in claimed]
    pages = sorted(
        d.name for d in DS.iterdir() if d.is_dir() and (d / "preview.html").is_file() and card(d.name)[1]
    )
    page_rows = []
    for page in pages:
        screen = page if page.endswith("Screen") else f"{page}Screen"
        if screen not in screens:
            errors.append(f"page {page}: no public {screen} in sample")
            continue
        path, summary = screens[screen]
        page_rows.append(
            f"| {page} | `{screen}` | [{Path(path).name}](../{path}) | {reference_stems(page)} | {summary} |"
        )
    lines = [
        BEGIN,
        "",
        f"### The design system's {len(rows)} components",
        "",
        "| Component | Composables | File | Group | References | Goldens | README | What it is |",
        "|---|---|---|---|---|---|---|---|",
        *rows,
        "",
        f"### Beyond the design system's exports: {len(beyond)}",
        "",
        "| Composable | File | What it is |",
        "|---|---|---|",
        *(f"| `{n}` | [{Path(core[n][0]).name}](../{core[n][0]}) | {core[n][1]} |" for n in beyond),
        "",
        f"### The design system's {len(page_rows)} pages, in `sample`",
        "",
        "| Page | Screen | File | References | What it is |",
        "|---|---|---|---|---|",
        *page_rows,
        "",
        END,
    ]
    return "\n".join(lines), errors


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="fail if docs/components.md is stale")
    a = ap.parse_args(argv)
    block, errors = generate()
    if errors:
        for e in errors:
            print(f"component_catalog: {e}", file=sys.stderr)
        return 1
    text = CATALOG.read_text(encoding="utf-8")
    if BEGIN not in text or END not in text:
        print(f"component_catalog: {CATALOG.relative_to(ROOT)} has no {BEGIN!r} … {END!r} block", file=sys.stderr)
        return 1
    current = text[text.index(BEGIN) : text.index(END) + len(END)]
    if a.check:
        if current != block:
            print(
                "component_catalog: docs/components.md is stale or was edited by hand; "
                "run python3 scripts/component_catalog.py",
                file=sys.stderr,
            )
            return 1
        print("component catalogue is up to date")
        return 0
    CATALOG.write_text(text.replace(current, block), encoding="utf-8")
    print(f"catalogue written: {CATALOG.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
