#!/usr/bin/env python3
"""Generate OldgeIcons.kt from the icon table of the vendored design system's bundle.js (B-11).

    python3 scripts/generate_icons.py            # write the file
    python3 scripts/generate_icons.py --check    # fail if the committed file differs

The bundle draws every icon as one `<path>` on a 24 × 24 grid with `fill="currentColor"` and
`fill-rule="evenodd"` (bundle.js, `function Icon`); nothing is stroked. So an icon is its path string
and nothing else, and the Kotlin keeps the string and parses it with Compose's own path parser —
a transcription of the path into nodes by this script would be a second parser nobody tested.
"""
import argparse
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
SOURCE = ROOT / "reference/design-system/components/bundle.js"
TARGET = ROOT / "oldge-core/src/commonMain/kotlin/io/github/youndie/oldge/icons/OldgeIcons.kt"


def icons():
    js = SOURCE.read_text()
    start = js.index("var PATHS = {")
    end = js.index("};", start)
    table = js[start:end]
    pairs = re.findall(r"^\s*'?([a-z][a-z-]*)'?\s*:\s*'([^']*)'", table, re.M)
    if not pairs:
        raise SystemExit("no icons found in bundle.js")
    return pairs


def pascal(name: str) -> str:
    return "".join(part[:1].upper() + part[1:] for part in name.split("-"))


def generate() -> str:
    pairs = icons()
    out = [
        "// GENERATED by scripts/generate_icons.py from reference/design-system/components/bundle.js.",
        "// Do not edit: `./gradlew check` runs the generator with --check.",
        "// The path strings are the bundle's, verbatim, so they are longer than a line may be.",
        '@file:Suppress("ktlint")',
        "",
        "package io.github.youndie.oldge.icons",
        "",
        "import androidx.compose.ui.graphics.vector.ImageVector",
        "",
        f"/** The design system's {len(pairs)} icons: single-path glyphs on a 24 × 24 grid, filled even-odd. */",
        "public object OldgeIcons {",
    ]
    for name, _ in pairs:
        out.append(f"    /** `{name}`. */")
        out.append(f"    public val {pascal(name)}: ImageVector by lazy {{ oldgeIcon(\"{name}\", OldgeIconPaths.getValue(\"{name}\")) }}")
        out.append("")
    out[-1:] = ["}", ""]
    out.append("/** Every icon's path, by the design system's name, in the bundle's order. */")
    out.append("internal val OldgeIconPaths: Map<String, String> =")
    out.append("    linkedMapOf(")
    for name, path in pairs:
        out.append(f"        \"{name}\" to \"{path}\",")
    out.append("    )")
    out.append("")
    return "\n".join(out)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    text = generate()
    if args.check:
        if not TARGET.exists() or TARGET.read_text() != text:
            print(f"{TARGET.relative_to(ROOT)} is stale: run python3 scripts/generate_icons.py", file=sys.stderr)
            return 1
        print(f"{TARGET.relative_to(ROOT)} matches bundle.js")
        return 0
    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(text)
    print(TARGET.relative_to(ROOT))
    return 0


if __name__ == "__main__":
    sys.exit(main())
